-- AlterTable
ALTER TABLE "config_facturacion" ADD COLUMN     "exoneradoParafiscales" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "empleados" ADD COLUMN     "arl" TEXT,
ADD COLUMN     "claseRiesgoArl" TEXT NOT NULL DEFAULT 'I';

-- AlterTable
ALTER TABLE "nominas" ADD COLUMN     "arl" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "cajaCompensacion" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "cesantias" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "costoTotal" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "exonerado" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "fsp" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "icbf" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "interesesCesantias" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "pensionPatronal" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "prima" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "saludPatronal" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "sena" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "totalAportesPatronales" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "totalPrestaciones" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vacaciones" DECIMAL(18,2) NOT NULL DEFAULT 0;
